/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author xp
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();  
    }
    
        private void bufferedwriter(String escrito, String rutaArchivo){
        try {
            //creamos un buffered writer y le indicamos donde lo guardara
            BufferedWriter bw = new BufferedWriter(new FileWriter(rutaArchivo));
            //le indicamos q ha de escribir
            bw.write(escrito); //escrito hace referencia al jTextArea1.getText() del boton de guardado    
            //cerramos el buffered writer
            bw.close();
            
        } catch (Exception e) {        
            System.out.println("fail");       
        }
    }
    
    private void bufferedwriter2(String escrito, String rutaArchivo){
        try {
            //creamos un buffered writer y le indicamos donde lo guardara
            BufferedWriter bw = new BufferedWriter(new FileWriter(rutaArchivo,true));
            //le indicamos q cree una linea antes de nada pues este va al boton de modificar
            bw.newLine();
            //le indicamos q ha de escribir
            bw.write(escrito);//escrito hace referencia al jTextArea1.getText() del boton de guardado
            //cerramos el buffered writer
            bw.close();
            
        } catch (Exception e) {        
            System.out.println("fail");       
        }
    }
    
    private void  bufferedreader(String rutaArchivo) throws FileNotFoundException{
        try{
            //creamos el buffered reader y le indicamos el archivo q va a leer
            BufferedReader br = new BufferedReader(new FileReader(rutaArchivo));
            //indicamos donde queremos q escriba el archivo q ha leido
            jTextArea1.read(br,br);
            //cerramos el buffered reader
            br.close();
        
        } catch(IOException e){
            System.out.println("fallo");
        }
            
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        abrir = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abrir.setText("abrir");
        abrir.setMaximumSize(new java.awt.Dimension(71, 23));
        abrir.setMinimumSize(new java.awt.Dimension(71, 23));
        abrir.setPreferredSize(new java.awt.Dimension(71, 23));
        abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirMouseClicked(evt);
            }
        });

        guardar.setText("guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        modificar.setText("modificar");
        modificar.setMaximumSize(new java.awt.Dimension(71, 23));
        modificar.setMinimumSize(new java.awt.Dimension(71, 23));
        modificar.setPreferredSize(new java.awt.Dimension(71, 23));
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(abrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        modificar.getAccessibleContext().setAccessibleName("modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMouseClicked
        
        //creamos el JFileChooser
        JFileChooser jF1= new JFileChooser(); 

    try{ 
        if(jF1.showOpenDialog(null)==jF1.APPROVE_OPTION){ 
            
            // le indicamos donde buscar
            String rutaArchivo = jF1.getSelectedFile().getAbsolutePath(); 
            //le pasamos al buffered reader q queremos q lea 
            bufferedreader(rutaArchivo);
        } 
    }catch (Exception ex){ 
        System.out.println("algo has roto"); 
    } 
    }//GEN-LAST:event_abrirMouseClicked

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        //creo el JFileChooser
        JFileChooser jF1= new JFileChooser(); 
    try{ 
        //si das al boton de guardar
        if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
            //le indicamos donde queremos guardar el archivo
            String rutaArchivo = jF1.getSelectedFile().getAbsolutePath(); 
            // 
            //le pasamos al buffered writer q queremos q escriba y donde
            bufferedwriter(jTextArea1.getText(),rutaArchivo);     
        } 
        //si se lia 
    }catch (Exception ex){ 
        System.out.println("algo has roto");
    } 
    }//GEN-LAST:event_guardarMouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        
         JFileChooser jF1= new JFileChooser(); 

    try{ 
        if(jF1.showSaveDialog(null)==jF1.APPROVE_OPTION){ 
            String rutaArchivo = jF1.getSelectedFile().getAbsolutePath(); 
            //Aqui ya tiens la ruta,,,ahora puedes crear un fichero n esa ruta y escribir lo k kieras... 
            
            bufferedwriter2(jTextArea1.getText(), rutaArchivo);
            
        } 
    }catch (Exception ex){ 
        ex.printStackTrace(); 
    } 
    
        
    }//GEN-LAST:event_modificarMouseClicked

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        File f = new File("Proyecto\\Nuevo documento de texto.xml");

        if (f.exists()) {
            System.out.println("Nombre: " + f.getName());
            System.out.println("Directorio padre: " + f.getParent());
            System.out.println("Ruta relativa: " + f.getPath());
            System.out.println("Ruta absoluta: " + f.getAbsolutePath());
        }

        

        Ventana obj_fichero = new Ventana();

      

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
